#pragma once

#include "boot_loader.h"
#include "efi.h"
#include "elf_loader.h"
#include "graphics.h"
#include "kernel.h"
#include "stdfunc.h"
#include "asm_loader.h"
#include "asm_kernel.h"
#include "descriptor.h"
#include "handler.h"
#include "keyboard.h"
#include "pic.h"
#include "stl.h"
#include "global.h"
#include "paging.h"
#include <stddef.h>
#include <cstdint>
#include <stdarg.h>